### ISSUE TITLE
Proposition: Combine data_format_converter and rss

### ISSUE THREAD

**Issue by ebebbington** [MikaelPorttila/rss#11]
Hello, i'm the author of https://github.com/ebebbington/data-format-converter, and i created it because I thought there were no converters as of yet. But only just discovered this project now.

I was curious if it was possible if we could combine, as in a single module to provide the following:
* CSV to JSON (taken from DFC)
* JSON to CSV (DFC)
* JSON to XML (DFC)
* XML to JSON (rss)

I've had trouble on making a xml to json converter, and resorted to using a public API, but your project provides that exact use, and my project provides the use for any other conversions. I think it would be great if we combine our efforts.

Although, this would require renaming this repository (to move my code here, as "rss" wouldn't be a fitting name for all the conversions it would provide), or two becoming one under my repository

Let me know what you think :)

**Comment by MikaelPorttila** [comment]
Hi!
This project is not a XML to JSON convert but a XML deserializer. 
It will read the XML feed files into very specific object structs and it would butcher any other generic XML-structure.

If you want a serious conversion you should look into porting some popular Node xml-lib into Deno, take the output and invoke JSON.stringify and you would have a better time than trying to use this lib.  :)

A Deno XML lib with deserialization is much needed but looking at the Deno discussions we won't have any std-variant soon.
