### ISSUE TITLE
Not "transpile safe"

### ISSUE THREAD

**Issue by paul90** [MikaelPorttila/rss#23]
Raising this follow on from discussion in https://github.com/denoland/deno/issues/10684 

For ease, I'll include kitsonk's observation inline here.

> Actually, I originally looked at this on my phone and didn't realise the problem. It isn't an swc issue. It is that the dependency, sadly, is not "transpile safe" and the way they are being exported does not trigger the "isolated modules" setting in the Deno CLI to give you an indication that it isn't working.
>
> The author of the package should be a) using .d.ts files for type only files and b) use export type and import type instead of just export and import.
>
> This is because when you are transpiling only (Deploy and --no-check), the transpiler has no idea that what you are trying to import/export is just a type that gets erased at runtime and so when it tries to do the named export (https://deno.land/x/rss@0.3.3/mod.ts#L8) it has no idea that that is just a type that got erased. You can read more about type only imports and exports here: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export. Again, we have the built in TypeScript settings trying to catch this, but the package author has found an interesting way to get around the --isolatedModules setting unintentionally, by doing export * in the ./types/mod.ts.

**Comment by MikaelPorttila** [comment]
Thank you for reporting this, release 0.3.4 should soon be available with a fix for the wrongful exports.
Did some testing and I was able to execute code using the ```--no-check``` option.

Please let me know if you have any trouble with the release.

**Comment by paul90** [comment]
Thanks. Works without any problems.
