### ISSUE TITLE
Provide consistent output for json feed mapping for all Feed types

### ISSUE THREAD

**Issue by searchableguy** [MikaelPorttila/rss#25]
Hello, I am using this module to build a news aggregator.  I fetch from many different feeds and feed type as a result. Atom feeds provide url in their `id` field while rss2 use `url` and `external url` for the same.  

When used with `outputJsonFeed` option, it should ideally settle on one field for the url or provide original FeedType. The FeedType it provides is that of jsonFeed which is expected but without the original information, you need to check for the type on your own to guess which properties will be available.

Few popular atom feeds don't provide a url in the ID consistently. They provide it in the alternative link field. This affects feeds on all google properties. A check here for ID and link field to see which one contains the url to post might be preferrable. 

```
https://developers.googleblog.com/feeds/posts/default
http://ai.googleblog.com/feeds/posts/default
https://googleprojectzero.blogspot.com/feeds/posts/default
https://security.googleblog.com/feeds/posts/default
```

https://github.com/MikaelPorttila/rss/blob/5238c5f4052ed5d8419e05105b82a838eb9df276/src/mapper.ts#L116

I think this should be entry.title for atom. Parsing atom feed normally only provides title instead of a nested  `title: { value: string }`

I am happy to contribute. Let me know what are your thoughts about the proposal.

**Comment by MikaelPorttila** [comment]
Hi! Thank you for posting this feedback and for showing interest for this project!

These feed formats won't never map 1:1 and by using the outputJsonFeed you will always lose some data during the mapping so my suggestion for your project would be to use the RSS2 and Atom formats directly and map those into your own internal types for a more robust solution.

Another option would provides a new api in this library that actually manage to map ATOM, RSS2 och JsonFeed into one single type that supports every use-case. That worked on without breaking the API.

Some data fields (title, summary, content and rights) in the Atom standard are using the so called "Text" type, which means that these field may contain different types of data such as "text", "html" and "xhtml". The type could be useful for some consumers of this library, the title field is actually ```title: { value: string, type: string }```.

The idea of exposing the original FeedType is good and I think we really should do that.

**Comment by searchableguy** [comment]
Thanks for the response. 

> Another option would provides a new api in this library that actually manage to map ATOM, RSS2 och JsonFeed into one single type that supports every use-case. That worked on without breaking the API.

That would be great. 

> The title field is actually title: { value: string, type: string }.

It might be a bug or an edge case (I haven't checked the actual parser code) but for the atom feeds provided in the example, I only get `title: string`. This is the same for several other atom feeds. 

> The idea of exposing the original FeedType is good and I think we really should do that.

Agreed.
