### ISSUE TITLE
Support `content:encoded` field

### ISSUE THREAD

**Issue by utamori** [MikaelPorttila/rss#41]
For medium, `content:encoded` is used.

https://medium.com/feed/invironment/tagged/food

https://github.com/rbren/rss-parser/issues/166

**Comment by MikaelPorttila** [comment]
Thank you for reporting this, I have added support for ```content:encoded``` in version 0.5.5.

The content can be found in the Feed Entry field ```content.value```.
Please try out the fix and let me know if it helped.

**Comment by utamori** [comment]
@MikaelPorttila 
I tried. It's working well. 😄 
Thanks you! 👍
