### ISSUE TITLE
Media RSS fields incorrectly typed for Youtube

### ISSUE THREAD

**Issue by Skalman** [MikaelPorttila/rss#46]
In a Youtube channel feed, (e.g. https://www.youtube.com/feeds/videos.xml?channel_id=UC2PA-AKmVpU6NKCGtZq_rKQ), the Media fields are grouped differently than in given types.

```ts
// Suggested by the types of this project
feed.entries[0][MediaRss.Community]?.[MediaRss.Statistics]?.views

// What actually works
feed.entries[0][MediaRss.Group]?.[MediaRss.Community]?.[MediaRss.Statistics]?.views
```

My understanding is that any Media RSS fields are allowed within a group, including another group, so the typing should be something like:

```ts
[MediaRssFields.Group]?: MediaRss;
```

Would you consider updating the types?

Thanks for a great library. This was exactly what I needed for my project! :heart:

**Comment by MikaelPorttila** [comment]
Thank you for this feedback and I'm glad to hear that you find the lib useful! :)
I have created a new release (0.5.7) and hopefully it will resolve any issues with the MediaRss typing.

Please give it a try 🦖

**Comment by Skalman** [comment]
Seems to work. Thanks a bunch!
