### ISSUE TITLE
Parsing invalid feed causes promise to never return

### ISSUE THREAD

**Issue by Skalman** [MikaelPorttila/rss#53]
Attempting to call `parseFeed` with invalid text string causes the resulting promise to never return.

I would have expected an error to be thrown.

```ts
// example.ts
import { parseFeed } from "https://deno.land/x/rss@1.0.0/mod.ts";
await parseFeed("dummy feed");
```

```
> deno run example.ts
error: Top-level await promise never resolved
await parseFeed("dummy feed");
^
    at <anonymous> (file:///.../example.ts:2:1)
```

**Comment by MikaelPorttila** [comment]
Hi @Skalman and thank you for taking your time to report on this issue! 👊

With the release of **1.0.1** this issue should have been resolved and it should match your expectation with an error being thrown when an invalid feed format is detected. (This is also how unsupported feed formats are handled today)

Please give the new package a try!

BR
Micke
