### ISSUE TITLE
JSR Repository support

### ISSUE THREAD

**Issue by MikaelPorttila** [MikaelPorttila/rss#55]
The folks behind Deno has released a new package distribution platform which can be viewed as the next iteration of NPMJS.
Denoland/X package distribution will not be removed just yet.

One downside of JSR is no support for HTTPS Imports and any packages using this RSS-package will have trouble distributing through JSR until it's available through the platform.

Todos:
[] HTTPS Import deps: sax-ts
[] Generate deno.json-manifest
[] Git actions for updating manifest version and deploy to JSR
[x] JSR Scope/Package registration
[] Documentation on how to install package through deno/x or JSR

**Comment by Skalman** [comment]
@MikaelPorttila, did you really register a scope? It seems like I was able to register the `@rss` scope - would you like to have it instead?

**Comment by Maxim-Mazurok** [comment]
> HTTPS Import deps: sax-ts

This should be done now: https://jsr.io/@maxim-mazurok/sax-ts :)

**Comment by totto2727** [comment]
I forked it and actually released it as a JSR package.
The code for this library itself required little modification and passed the tests for the system at hand.
I am concerned that the CI tests are failing...

https://jsr.io/@totto/rss
https://github.com/totto2727-org/rss

**Comment by MikaelPorttila** [comment]
@Skalman I'll just put the package under my own scope, keep the @rss for yourself and use it when you write an even better feed parser! 😊

@Maxim-Mazurok Splendid work man, I'm using the new feed now in production and it's working well.👌

@totto2727 Thanks for trying! 🤘 I have seen that CI issue before, it pops up shortly after a new Deno-release if you are using the latest version of the deno-setup-task. It will probebly work if you rerun the workflow again. 

There has been a JSR-package repo for a while but I got busy with other things, it's live now: [https://jsr.io/@mikaelporttila/rss](https://jsr.io/@mikaelporttila/rss)
