### ISSUE TITLE
deno.land/x upload?

### ISSUE THREAD

**Issue by CodingCarter** [MikaelPorttila/rss#6]
Hi, I used your module and it's great, but do you think you could add your module to [Deno's Third Party Modules Index](https://deno.land/x/#add).  It would help the development of the module because your module would appear first on the Deno's third party index search.  Thanks for the module and reading!

**Comment by MikaelPorttila** [comment]
Hi,
Thank you for trying out the module and I'm glad to hear the positive feedback.
You can now install the rss module using the Deno third-party url: **https://deno.land/x/rss/mod.ts**

Happy coding!
